#version: '3.9'
services:
  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
  nginx:
    image: nginx
    healthcheck:
      test: ["curl", "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - "80:80"
    depends_on:
      - symfony
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secretpassword