#version: '3.9'
services:
  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - mon-volume: var/cache
    # healthcheck:
    #   test: ["curl", "localhost"]
    #   interval: 1m30s
    #   timeout: 30s
    #   retries: 5
    #   start_period: 30s
    depends_on:
      - db
    networks:
      - network1
      - network2
  nginx:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      symfony:
        condition: service_healthy
  networks:
      - network1
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secretpassword
    networks:
      - network2

volumes:
  mon-volume:
    driver: local

networks:
  network1:
    driver: bridge
  network2:
    driver: bridge